export const translations = {
  en: {
    // Welcome
    'app_title': 'SkillUp',
    'app_subtitle': 'Grow Your Skills, Grow Your Income.',
    'choose_language': 'Choose Your Language',
    'english': 'English',
    'hindi': 'हिंदी',
    'gujarati': 'ગુજરાતી',

    // Phone Input
    'whats_your_number': "What's your number?",
    'enter_mobile_prompt': 'Enter your mobile number to create your account.',
    'phone_placeholder': '98765 43210',
    'otp_info': "We'll send an OTP to verify.",
    'continue': 'Continue',

    // OTP
    'verify_your_number': 'Verify Your Number',
    'enter_otp_prompt': 'Enter the 4-digit code sent to you.',
    'verify': 'Verify',
    'resend_otp': 'Resend OTP',
    'resend_otp_in': 'Resend OTP in',

    // Home
    'hi_user': 'Hi, {name} 👋',
    'your_daily_goal': 'Your Daily Goal',
    'lesson_today': 'Lesson Today',
    'todays_lesson_done': "Today's Lesson Done!",
    'keep_learning': 'Keep Learning!',
    'modules': 'Modules',
    'start': 'Start',

    // Courses
    'course_catalog': 'Course Catalog',
    'category': 'Category',
    'all': 'All',
    'technical': 'Technical',
    'finance': 'Finance',
    'personal_growth': 'Personal Growth',
    'certified_courses_only': 'Certified Courses Only',
    'certified': 'Certified',
    'practice': 'Practice',
    'mins': 'mins',
    'no_courses_found': 'No courses match your filters.',
    
    // Course Details
    'duration': 'Duration',
    'level': 'Level',
    'certificate': 'Certificate',
    'yes': 'Yes',
    'no': 'No',
    'lessons_count': 'Lessons ({count})',
    'enroll_now': 'Enroll Now',
    'watch_lesson': 'Watch Lesson',
    'mark_as_completed': 'Mark as Completed',

    // Jobs/Career
    'career_hub': 'Career Hub',
    'apply_now': 'Apply Now',

    // Wallet/Finances
    'my_finances': 'My Finances',
    'monthly_income': 'Monthly Income',
    'monthly_expenses': 'Monthly Expenses',
    'school_fees': "Children's School Fees",
    'house_rent': 'House Rent',
    'household_expenses': 'Household Expenses',
    'transport_fuel': 'Transportation or Fuel',
    'other': 'Other',
    'total_expenses': 'Total Expenses',
    'financial_summary': 'Financial Summary',
    'monthly_savings': 'Monthly Savings',
    'suggested_investment': 'Suggested Investment (30%)',
    'daily_saving_goal': 'Daily Saving Goal',
    'view_breakdown': 'View Expense Breakdown',
    'close': 'Close',
    'income': 'Income',
    'expenses': 'Expenses',
    'savings': 'Savings',
    'track_daily_income': 'Track Daily Income',
    'daily_income_tracker': 'Daily Income Tracker',
    'log_your_earnings': 'Log Your Earnings',
    'date': 'Date',
    'income_today': "Today's Income (₹)",
    'add_earning': 'Add Earning',
    'monthly_summary_for': 'Monthly Summary for {month}',
    'total_earned': 'Total Earned',
    'no_earnings_month': 'No earnings logged for this month.',
    'vs_previous_months': 'vs. Previous Months',

    // Savings Goals
    'my_savings_goals': 'My Savings Goals',
    'add_new_goal': '+ Add New Goal',
    'goal_colon': 'Goal:',
    'saved_colon': 'Saved:',
    'add_money': 'Add Money',
    'withdraw': 'Withdraw',
    'total_saved_in_goals': 'Total Saved in Goals',
    'create_new_goal': 'Create a New Savings Goal',
    'goal_name_placeholder': 'e.g., New Phone',
    'goal_amount_placeholder': 'e.g., 15000',
    'goal_name': 'Goal Name',
    'goal_amount': 'Goal Amount',
    'optional_description': 'Description (Optional)',
    'save_goal': 'Save Goal',
    'manage_funds_for': 'Manage Funds for "{goalName}"',
    'amount_to_add': 'Amount to Add',
    'amount_to_withdraw': 'Amount to Withdraw',
    'confirm_payment': 'Confirm Payment',
    'confirm_withdrawal': 'Confirm Withdrawal',
    'payment_successful': 'Payment Successful!',
    'funds_withdrawn': 'Funds Withdrawn',
    'cancel': 'Cancel',
    'securely_save_info': 'Securely save for your goals anytime and withdraw when needed.',

    // Profile
    'my_profile': 'My Profile',
    'edit_profile': 'Edit Profile',
    'save_changes': 'Save Changes',
    'full_name': 'Full Name',
    'email_address': 'Email Address',
    'currently_working_with': 'Currently working with',
    'select_company': 'Select Company',

    // Government Schemes
    'government_schemes_title': 'Government Schemes',
    'pmjjby_title': 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
    'pmjjby_desc': 'Life insurance coverage at low premium rates.',
    'pmjjby_details': 'Offers ₹2 lakh coverage for accidental or natural death.',
    'pmsby_title': 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
    'pmsby_desc': 'Provides accident insurance for low-income workers.',
    'pmsby_details': 'Premium ₹12 per year, coverage up to ₹2 lakh for accidental death/disability.',
    'apy_title': 'Atal Pension Yojana (APY)',
    'apy_desc': 'Pension scheme for unorganized sector workers.',
    'apy_details': 'Offers ₹1,000–₹5,000 per month after 60 years of age.',
    'learn_more': 'Learn More',
    'visit_official_site': 'Visit Official Site',

    // Nav Bar
    'home': 'Home',
    'courses': 'Courses',
    'schemes': 'Schemes',
    'wallet': 'Wallet',
    'career': 'Career',
    'profile': 'Profile',
  },
  hi: {
    'app_title': 'स्किलअप',
    'app_subtitle': 'अपना कौशल बढ़ाएं, अपनी आय बढ़ाएं।',
    'choose_language': 'अपनी भाषा चुनें',
    'english': 'English',
    'hindi': 'हिंदी',
    'gujarati': 'ગુજરાતી',
    'whats_your_number': 'आपका नंबर क्या है?',
    'enter_mobile_prompt': 'अपना खाता बनाने के लिए अपना मोबाइल नंबर दर्ज करें।',
    'phone_placeholder': '98765 43210',
    'otp_info': 'हम पुष्टि के लिए एक OTP भेजेंगे।',
    'continue': 'जारी रखें',
    'verify_your_number': 'अपना नंबर सत्यापित करें',
    'enter_otp_prompt': 'आपको भेजा गया 4-अंकीय कोड दर्ज करें।',
    'verify': 'सत्यापित करें',
    'resend_otp': 'OTP फिर से भेजें',
    'resend_otp_in': 'OTP फिर से भेजें',
    'hi_user': 'नमस्ते, {name} 👋',
    'your_daily_goal': 'आपका दैनिक लक्ष्य',
    'lesson_today': 'आज का पाठ',
    'todays_lesson_done': 'आज का पाठ हो गया!',
    'keep_learning': 'सीखते रहें!',
    'modules': 'मॉड्यूल',
    'start': 'शुरू करें',
    'course_catalog': 'कोर्स कैटलॉग',
    'category': 'श्रेणी',
    'all': 'सभी',
    'technical': 'तकनीकी',
    'finance': 'वित्त',
    'personal_growth': 'व्यक्तिगत विकास',
    'certified_courses_only': 'केवल प्रमाणित पाठ्यक्रम',
    'certified': 'प्रमाणित',
    'practice': 'अभ्यास',
    'mins': 'मिनट',
    'no_courses_found': 'आपके फ़िल्टर से कोई कोर्स मेल नहीं खाता।',
    'duration': 'अवधि',
    'level': 'स्तर',
    'certificate': 'प्रमाणपत्र',
    'yes': 'हाँ',
    'no': 'नहीं',
    'lessons_count': 'पाठ ({count})',
    'watch_lesson': 'पाठ देखें',
    'mark_as_completed': 'पूर्ण के रूप में चिह्नित करें',
    'career_hub': 'करियर हब',
    'apply_now': 'अभी आवेदन करें',
    'my_finances': 'मेरी वित्तीय स्थिति',
    'monthly_income': 'मासिक आय',
    'monthly_expenses': 'मासिक खर्च',
    'school_fees': 'बच्चों की स्कूल फीस',
    'house_rent': 'घर का किराया',
    'household_expenses': 'घरेलू खर्च',
    'transport_fuel': 'परिवहन या ईंधन',
    'other': 'अन्य',
    'total_expenses': 'कुल खर्च',
    'financial_summary': 'वित्तीय सारांश',
    'monthly_savings': 'मासिक बचत',
    'suggested_investment': 'सुझाई गई निवेश (30%)',
    'daily_saving_goal': 'दैनिक बचत लक्ष्य',
    'view_breakdown': 'खर्च का विवरण देखें',
    'close': 'बंद करें',
    'income': 'आय',
    'expenses': 'खर्च',
    'savings': 'बचत',
    'track_daily_income': 'दैनिक आय ट्रैक करें',
    'daily_income_tracker': 'दैनिक आय ट्रैकर',
    'log_your_earnings': 'अपनी कमाई लॉग करें',
    'date': 'तारीख',
    'income_today': 'आज की आय (₹)',
    'add_earning': 'कमाई जोड़ें',
    'monthly_summary_for': '{month} के लिए मासिक सारांश',
    'total_earned': 'कुल कमाई',
    'no_earnings_month': 'इस महीने कोई कमाई दर्ज नहीं की गई।',
    'vs_previous_months': 'बनाम पिछले महीने',
    'my_savings_goals': 'मेरे बचत लक्ष्य',
    'add_new_goal': '+ नया लक्ष्य जोड़ें',
    'goal_colon': 'लक्ष्य:',
    'saved_colon': 'बचत:',
    'add_money': 'पैसे जोड़ें',
    'withdraw': 'पैसे निकालें',
    'total_saved_in_goals': 'लक्ष्यों में कुल बचत',
    'create_new_goal': 'एक नया बचत लक्ष्य बनाएं',
    'goal_name_placeholder': 'उदा., नया फ़ोन',
    'goal_amount_placeholder': 'उदा., 15000',
    'goal_name': 'लक्ष्य का नाम',
    'goal_amount': 'लक्ष्य राशि',
    'optional_description': 'विवरण (वैकल्पिक)',
    'save_goal': 'लक्ष्य सहेजें',
    'manage_funds_for': '"{goalName}" के लिए फंड प्रबंधित करें',
    'amount_to_add': 'जोड़ने के लिए राशि',
    'amount_to_withdraw': 'निकालने के लिए राशि',
    'confirm_payment': 'भुगतान की पुष्टि करें',
    'confirm_withdrawal': 'निकासी की पुष्टि करें',
    'payment_successful': 'भुगतान सफल!',
    'funds_withdrawn': 'धनराशि निकाली गई',
    'cancel': 'रद्द करें',
    'securely_save_info': 'अपने लक्ष्यों के लिए कभी भी सुरक्षित रूप से बचत करें और जरूरत पड़ने पर निकालें।',
    'my_profile': 'मेरी प्रोफ़ाइल',
    'edit_profile': 'प्रोफ़ाइल संपादित करें',
    'save_changes': 'बदलाव सहेजें',
    'full_name': 'पूरा नाम',
    'email_address': 'ईमेल पता',
    'currently_working_with': 'वर्तमान में इनके साथ काम कर रहे हैं',
    'select_company': 'कंपनी चुनें',
    'government_schemes_title': 'सरकारी योजनाएं',
    'pmjjby_title': 'प्रधानमंत्री जीवन ज्योति बीमा योजना (पीएमजेजेबीवाई)',
    'pmjjby_desc': 'कम प्रीमियम दरों पर जीवन बीमा कवरेज।',
    'pmjjby_details': 'आकस्मिक या प्राकृतिक मृत्यु के लिए ₹2 लाख का कवरेज प्रदान करता है।',
    'pmsby_title': 'प्रधानमंत्री सुरक्षा बीमा योजना (पीएमएसबीवाई)',
    'pmsby_desc': 'कम आय वाले श्रमिकों के लिए दुर्घटना बीमा प्रदान करता है।',
    'pmsby_details': 'प्रीमियम ₹12 प्रति वर्ष, आकस्मिक मृत्यु/विकलांगता के लिए ₹2 लाख तक का कवरेज।',
    'apy_title': 'अटल पेंशन योजना (एपीवाई)',
    'apy_desc': 'असंगठित क्षेत्र के श्रमिकों के लिए पेंशन योजना।',
    'apy_details': '60 वर्ष की आयु के बाद ₹1,000–₹5,000 प्रति माह प्रदान करता है।',
    'learn_more': 'और जानें',
    'visit_official_site': 'आधिकारिक साइट पर जाएं',
    'home': 'होम',
    'courses': 'कोर्स',
    'schemes': 'योजनाएं',
    'wallet': 'बटुआ',
    'career': 'करियर',
    'profile': 'प्रोफ़ाइल',
  },
  gu: {
    'app_title': 'સ્કિલઅપ',
    'app_subtitle': 'તમારી કુશળતા વધારો, તમારી આવક વધારો.',
    'choose_language': 'તમારી ભાષા પસંદ કરો',
    'english': 'English',
    'hindi': 'हिंदी',
    'gujarati': 'ગુજરાતી',
    'whats_your_number': 'તમારો નંબર શું છે?',
    'enter_mobile_prompt': 'તમારું એકાઉન્ટ બનાવવા માટે તમારો મોબાઇલ નંબર દાખલ કરો.',
    'phone_placeholder': '98765 43210',
    'otp_info': 'અમે ચકાસણી માટે એક OTP મોકલીશું.',
    'continue': 'આગળ વધો',
    'verify_your_number': 'તમારો નંબર ચકાસો',
    'enter_otp_prompt': 'તમને મોકલેલો 4-અંકનો કોડ દાખલ કરો.',
    'verify': 'ચકાસો',
    'resend_otp': 'OTP ફરીથી મોકલો',
    'resend_otp_in': 'OTP ફરીથી મોકલો',
    'hi_user': 'કેમ છો, {name} 👋',
    'your_daily_goal': 'તમારું દૈનિક લક્ષ્ય',
    'lesson_today': 'આજનો પાઠ',
    'todays_lesson_done': 'આજનો પાઠ પૂર્ણ થયો!',
    'keep_learning': 'શીખતા રહો!',
    'modules': 'મોડ્યુલો',
    'start': 'શરૂ કરો',
    'course_catalog': 'કોર્સ કેટલોગ',
    'category': 'શ્રેણી',
    'all': 'બધા',
    'technical': 'તકનીકી',
    'finance': 'નાણાકીય',
    'personal_growth': 'વ્યક્તિગત વિકાસ',
    'certified_courses_only': 'ફક્ત પ્રમાણિત курсы',
    'certified': 'પ્રમાણિત',
    'practice': 'પ્રેક્ટિસ',
    'mins': 'મિનિટ',
    'no_courses_found': 'તમારા ફિલ્ટર્સ સાથે કોઈ કોર્સ મેળ ખાતો નથી.',
    'duration': 'અવધિ',
    'level': 'સ્તર',
    'certificate': 'પ્રમાણપત્ર',
    'yes': 'હા',
    'no': 'ના',
    'lessons_count': 'પાઠ ({count})',
    'watch_lesson': 'પાઠ જુઓ',
    'mark_as_completed': 'પૂર્ણ તરીકે ચિહ્નિત કરો',
    'career_hub': 'કારકિર્દી હબ',
    'apply_now': 'હવે અરજી કરો',
    'my_finances': 'મારી નાણાકીય સ્થિતિ',
    'monthly_income': 'માસિક આવક',
    'monthly_expenses': 'માસિક ખર્ચ',
    'school_fees': 'બાળકોની શાળા ફી',
    'house_rent': 'ઘરનું ભાડું',
    'household_expenses': 'ઘરગથ્થુ ખર્ચ',
    'transport_fuel': 'પરિવહન અથવા બળતણ',
    'other': 'અન્ય',
    'total_expenses': 'કુલ ખર્ચ',
    'financial_summary': 'નાણાકીય સારાંશ',
    'monthly_savings': 'માસિક બચત',
    'suggested_investment': 'સૂચિત રોકાણ (30%)',
    'daily_saving_goal': 'દૈનિક બચત લક્ષ્ય',
    'view_breakdown': 'ખર્ચનું વિવરણ જુઓ',
    'close': 'બંધ કરો',
    'income': 'આવક',
    'expenses': 'ખર્ચ',
    'savings': 'બચત',
    'track_daily_income': 'દૈનિક આવક ટ્રૅક કરો',
    'daily_income_tracker': 'દૈનિક આવક ટ્રેકર',
    'log_your_earnings': 'તમારી કમાણી લોગ કરો',
    'date': 'તારીખ',
    'income_today': 'આજની આવક (₹)',
    'add_earning': 'કમાણી ઉમેરો',
    'monthly_summary_for': '{month} માટે માસિક સારાંશ',
    'total_earned': 'કુલ કમાણી',
    'no_earnings_month': 'આ મહિને કોઈ કમાણી લોગ થયેલ નથી.',
    'vs_previous_months': 'વિ. પાછલા મહિનાઓ',
    'my_savings_goals': 'મારા બચત લક્ષ્યો',
    'add_new_goal': '+ નવું લક્ષ્ય ઉમેરો',
    'goal_colon': 'લક્ષ્ય:',
    'saved_colon': 'બચત:',
    'add_money': 'પૈસા ઉમેરો',
    'withdraw': 'પૈસા ઉપાડો',
    'total_saved_in_goals': 'લક્ષ્યોમાં કુલ બચત',
    'create_new_goal': 'નવું બચત લક્ષ્ય બનાવો',
    'goal_name_placeholder': 'દા.ત., નવો ફોન',
    'goal_amount_placeholder': 'દા.ત., 15000',
    'goal_name': 'લક્ષ્યનું નામ',
    'goal_amount': 'લક્ષ્ય રકમ',
    'optional_description': 'વર્ણન (વૈકલ્પિક)',
    'save_goal': 'લક્ષ્ય સાચવો',
    'manage_funds_for': '"{goalName}" માટે ભંડોળનું સંચાલન કરો',
    'amount_to_add': 'ઉમેરવાની રકમ',
    'amount_to_withdraw': 'ઉપાડવાની રકમ',
    'confirm_payment': 'ચુકવણીની પુષ્ટિ કરો',
    'confirm_withdrawal': 'ઉપાડની પુષ્ટિ કરો',
    'payment_successful': 'ચુકવણી સફળ!',
    'funds_withdrawn': 'ભંડોળ ઉપાડવામાં આવ્યું',
    'cancel': 'રદ કરો',
    'securely_save_info': 'તમારા લક્ષ્યો માટે ગમે ત્યારે સુરક્ષિત રીતે બચત કરો અને જરૂર પડ્યે ઉપાડો.',
    'my_profile': 'મારી પ્રોફાઇલ',
    'edit_profile': 'પ્રોફાઇલ સંપાદિત કરો',
    'save_changes': 'ફેરફારો સાચવો',
    'full_name': 'પૂરું નામ',
    'email_address': 'ઇમેઇલ સરનામું',
    'currently_working_with': 'હાલમાં આની સાથે કામ કરી રહ્યા છીએ',
    'select_company': 'કંપની પસંદ કરો',
    'government_schemes_title': 'સરકારી યોજનાઓ',
    'pmjjby_title': 'પ્રધાનમંત્રી જીવન જ્યોતિ વીમા યોજના (પીએમજેજેબીવાય)',
    'pmjjby_desc': 'ઓછા પ્રીમિયમ દરે જીવન વીમા કવરેજ.',
    'pmjjby_details': 'આકસ્મિક અથવા કુદરતી મૃત્યુ માટે ₹2 લાખનું કવરેજ આપે છે.',
    'pmsby_title': 'પ્રધાનમંત્રી સુરક્ષા વીમા યોજના (પીએમએસબીવાય)',
    'pmsby_desc': 'ઓછી આવક ધરાવતા કામદારો માટે અકસ્માત વીમો પૂરો પાડે છે.',
    'pmsby_details': 'પ્રીમિયમ ₹12 પ્રતિ વર્ષ, આકસ્મિક મૃત્યુ/અપંગતા માટે ₹2 લાખ સુધીનું કવરેજ.',
    'apy_title': 'અટલ પેન્શન યોજના (એપીવાય)',
    'apy_desc': 'અસંગઠિત ક્ષેત્રના કામદારો માટે પેન્શન યોજના.',
    'apy_details': '60 વર્ષની વય પછી દર મહિને ₹1,000–₹5,000 ઓફર કરે છે.',
    'learn_more': 'વધુ શીખો',
    'visit_official_site': 'સત્તાવાર સાઇટની મુલાકાત લો',
    'home': 'હોમ',
    'courses': 'કોર્સ',
    'schemes': 'યોજનાઓ',
    'wallet': 'વોલેટ',
    'career': 'કારકિર્દી',
    'profile': 'પ્રોફાઇલ',
  }
};